### ISSUE TITLE
Notification Error with Gmail SMTP

### ISSUE THREAD

**Issue by ilkevinli** [Finsys/dockhand#30]
Hi,
     I am trying to setup notifications with gmail SMTP. I use the same settings I have in other setups and that works without issue. Below is the error I am getting from (Dockhand logs):

[dockhand] 2025-12-30T20:59:31.249664404Z [Notifications] SMTP send failed: TypeError: Cannot destructure property 'subject' from null or undefined value
[dockhand] 2025-12-30T20:59:31.250049412Z  command: "CONN",
[dockhand] 2025-12-30T20:59:31.250098649Z     code: "ESOCKET"
[dockhand] 2025-12-30T20:59:31.250133957Z 
[dockhand] 2025-12-30T20:59:31.250150010Z       at checkServerIdentity (node:tls:218:51)
[dockhand] 2025-12-30T20:59:31.250179432Z       at handshake (node:net:317:40)

Any suggestions ? Thanks

**Comment by jotka** [comment]
fixed, goes out with 1.0.5 

<img width="916" height="223" alt="Image" src="https://github.com/user-attachments/assets/2a61af88-8726-4e43-a423-c862d3ca10f9" />

**Comment by ilkevinli** [comment]
Thank you. great support !

**Comment by jotka** [comment]
hi @ilkevinli try this one `fnsys/dockhand:9ecde674`, please. I'ts 1.0.5 RC.

**Comment by jotka** [comment]
`fnsys/dockhand:latest` (or `v1.0.5`) released. Closing this one, feel free to reopen in you find issues. thanks!

**Comment by ilkevinli** [comment]
The error is still occurring for me. I tried deleting and setting it up again, but I am still getting the following error:

[dockhand] 2026-01-04T00:02:12.896217404Z [Notifications] SMTP send failed: TypeError: Cannot destructure property 'subject' from null or undefined value
[dockhand] 2026-01-04T00:02:12.896582682Z  command: "CONN",
[dockhand] 2026-01-04T00:02:12.896625705Z     code: "ESOCKET"
[dockhand] 2026-01-04T00:02:12.896647706Z 
[dockhand] 2026-01-04T00:02:12.896662952Z       at checkServerIdentity (node:tls:218:51)
[dockhand] 2026-01-04T00:02:12.896680029Z       at handshake (node:net:317:40)
[dockhand] 2026-01-04T00:02:12.896731663Z

**Comment by jotka** [comment]
hi @ilkevinli , please confirm you doing this way:

 first, an app assword

  1. Go to https://myaccount.google.com/apppasswords
  2. Generate a new app password for "Mail"
  3. Copy the 16-character password (ignore spaces)
  4. Use this instead of your regular Gmail password

then

```
  | Setting         | Value                                   |
  |-----------------|-----------------------------------------|
  | SMTP host       | smtp.gmail.com                          |
  | Port            | 587                                     |
  | TLS/SSL         | No ⚠️                                   |
  | Skip TLS verify | No                                      |
  | Username        | your Gmail address                      |
  | Password        | App Password (16 characters, no spaces) |
```

Why TLS/SSL = No?

Port 587 uses STARTTLS - it connects first, then automatically upgrades to encrypted. Setting TLS/SSL to "Yes" tries immediate encryption, which port 587 doesn't support.

Alternative: Use port 465 with TLS/SSL = Yes (older method, but also works).

<img width="776" height="764" alt="Image" src="https://github.com/user-attachments/assets/2c6bb243-88de-412a-aed0-b11b1d888768" />

**Comment by ilkevinli** [comment]
Hi,
     I did have the TLS/SSL option on.  Once I turned it off, its now working. I had to use the SSL option on my other applications so its weird that its working without it here. Thanks for your help and support. This is an excellent application.

**Comment by jotka** [comment]
hi @ilkevinli 
here's the explanation, not to keep you worried.

It works for you "without TLS" because in the nodemailer library (which Dockhand uses), the option secure: false does not mean encryption is disabled. On port 587, it enables STARTTLS mode. The connection starts as plain text but is immediately upgraded to a secure TLS channel. This is the standard and secure method for Gmail.
​

Technical Details (Port 587 vs. 465)

You have enabled the "TLS/SSL" option (setting secure: true) while using port 587. This is a classic SMTP configuration mismatch:

```
| Port | UI Option (Nodemailer)  | Encryption Mode          | Result for Gmail                                                                                                                                     |
| ---- | ----------------------- | ------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| 587  | TLS Off (secure: false) | STARTTLS (Opportunistic) | Works. Connection is established, server advertises encryption support, client sends STARTTLS command, and the channel becomes secure. |
| 587  | TLS On (secure: true)   | Implicit TLS (Forced)    | Fails. Client expects immediate encryption handshake, but the server is waiting for a text command. Connection drops (ESOCKET / timeout).            |
| 465  | TLS On (secure: true)   | Implicit TLS (Forced)    | Works. This is the legacy standard where the entire connection is encrypted from the very first byte                                      |
```
